package com.example.model

data class Currency(
    val code: String,
    val name: String,
    val frenchName: String,
    val symbol: String,
    val flag: String,
    val countryCode: String,
    val defaultRateToUSD: Double = 1.0
)

object CurrencyCatalog {
    val currencies = listOf(
        // Devises Majeures & G10
        Currency("USD", "US Dollar", "Dollar Américain", "$", "🇺🇸", "US", 1.0),
        Currency("EUR", "Euro", "Euro", "€", "🇪🇺", "EU", 0.9234),
        Currency("GBP", "British Pound", "Livre Sterling", "£", "🇬🇧", "GB", 0.7885),
        Currency("JPY", "Japanese Yen", "Yen Japonais", "¥", "🇯🇵", "JP", 154.20),
        Currency("CHF", "Swiss Franc", "Franc Suisse", "CHF", "🇨🇭", "CH", 0.8845),
        Currency("CAD", "Canadian Dollar", "Dollar Canadien", "CA$", "🇨🇦", "CA", 1.3780),
        Currency("AUD", "Australian Dollar", "Dollar Australien", "A$", "🇦🇺", "AU", 1.5280),
        Currency("NZD", "New Zealand Dollar", "Dollar Néo-Zélandais", "NZ$", "🇳🇿", "NZ", 1.6620),
        Currency("SEK", "Swedish Krona", "Couronne Suédoise", "kr", "🇸🇪", "SE", 10.62),
        Currency("NOK", "Norwegian Krone", "Couronne Norvégienne", "kr", "🇳🇴", "NO", 10.88),
        Currency("DKK", "Danish Krone", "Couronne Danoise", "kr", "🇩🇰", "DK", 6.89),

        // Afrique (Ouest, Centre, Nord, Est, Sud)
        Currency("XOF", "West African CFA Franc", "Franc CFA (BCEAO - UEMOA)", "CFA", "🌍", "XOF", 605.70),
        Currency("XAF", "Central African CFA Franc", "Franc CFA (BEAC - CEMAC)", "FCFA", "🌍", "XAF", 605.70),
        Currency("GNF", "Guinean Franc", "Franc Guinéen", "FG", "🇬🇳", "GN", 8600.0),
        Currency("MAD", "Moroccan Dirham", "Dirham Marocain", "MAD", "🇲🇦", "MA", 9.9850),
        Currency("DZD", "Algerian Dinar", "Dinar Algérien", "DA", "🇩🇿", "DZ", 134.50),
        Currency("TND", "Tunisian Dinar", "Dinar Tunisien", "DT", "🇹🇳", "TN", 3.12),
        Currency("EGP", "Egyptian Pound", "Livre Égyptienne", "E£", "🇪🇬", "EG", 48.50),
        Currency("NGN", "Nigerian Naira", "Naira Nigérian", "₦", "🇳🇬", "NG", 1500.0),
        Currency("GHS", "Ghanaian Cedi", "Cedi Ghanéen", "GH₵", "🇬🇭", "GH", 15.20),
        Currency("ZAR", "South African Rand", "Rand Sud-Africain", "R", "🇿🇦", "ZA", 18.15),
        Currency("KES", "Kenyan Shilling", "Shilling Kényan", "KSh", "🇰🇪", "KE", 129.50),
        Currency("CDF", "Congolese Franc", "Franc Congolais (RDC)", "FC", "🇨🇩", "CD", 2850.0),
        Currency("MGA", "Malagasy Ariary", "Ariary Malgache", "Ar", "🇲🇬", "MG", 4550.0),
        Currency("MUR", "Mauritian Rupee", "Roupie Mauricienne", "₨", "🇲🇺", "MU", 46.20),
        Currency("SCR", "Seychellois Rupee", "Roupie Seychelloise", "SR", "🇸🇨", "SC", 13.85),
        Currency("ETB", "Ethiopian Birr", "Birr Éthiopien", "Br", "🇪🇹", "ET", 57.50),
        Currency("RWF", "Rwandan Franc", "Franc Rwandais", "FRw", "🇷🇼", "RW", 1315.0),
        Currency("TZS", "Tanzanian Shilling", "Shilling Tanzanien", "TSh", "🇹🇿", "TZ", 2620.0),
        Currency("UGX", "Ugandan Shilling", "Shilling Ougandais", "USh", "🇺🇬", "UG", 3710.0),
        Currency("AOA", "Angolan Kwanza", "Kwanza Angolais", "Kz", "🇦🇴", "AO", 855.0),
        Currency("BWP", "Botswanan Pula", "Pula Botswanais", "P", "🇧🇼", "BW", 13.60),
        Currency("CVE", "Cape Verdean Escudo", "Escudo Cap-Verdien", "CVE", "🇨🇻", "CV", 102.0),
        Currency("DJF", "Djiboutian Franc", "Franc Djiboutien", "Fdj", "🇩🇯", "DJ", 177.72),
        Currency("ERN", "Eritrean Nakfa", "Nakfa Érythréen", "Nfk", "🇪🇷", "ER", 15.0),
        Currency("GMD", "Gambian Dalasi", "Dalasi Gambien", "D", "🇬🇲", "GM", 69.50),
        Currency("KMF", "Comorian Franc", "Franc Comorien", "CF", "🇰🇲", "KM", 454.0),
        Currency("LRD", "Liberian Dollar", "Dollar Libérien", "L$", "🇱🇷", "LR", 194.0),
        Currency("LSL", "Lesotho Loti", "Loti Lesothan", "L", "🇱🇸", "LS", 18.15),
        Currency("LYD", "Libyan Dinar", "Dinar Libyen", "LD", "🇱🇾", "LY", 4.85),
        Currency("MZN", "Mozambican Metical", "Metical Mozambicain", "MT", "🇲🇿", "MZ", 63.90),
        Currency("NAD", "Namibian Dollar", "Dollar Namibien", "N$", "🇳🇦", "NA", 18.15),
        Currency("SDG", "Sudanese Pound", "Livre Soudanaise", "SDG", "🇸🇩", "SD", 601.0),
        Currency("SLE", "Sierra Leonean Leone", "Leone Sierra-Léonais", "Le", "🇸🇱", "SL", 22.50),
        Currency("SOS", "Somali Shilling", "Shilling Somalien", "Sh.So.", "🇸🇴", "SO", 571.0),
        Currency("STN", "São Tomé & Príncipe Dobra", "Dobra Santoméen", "Db", "🇸🇹", "ST", 22.65),
        Currency("SZL", "Swazi Lilangeni", "Lilangeni Swazilandais", "E", "🇸🇿", "SZ", 18.15),
        Currency("ZMW", "Zambian Kwacha", "Kwacha Zambien", "ZK", "🇿🇲", "ZM", 25.80),
        Currency("MWK", "Malawian Kwacha", "Kwacha Malawite", "MK", "🇲🇼", "MW", 1735.0),
        Currency("BIF", "Burundian Franc", "Franc Burundais", "FBu", "🇧🇮", "BI", 2880.0),
        Currency("MRU", "Mauritanian Ouguiya", "Ouguiya Mauritanien", "MRU", "🇲🇷", "MR", 39.80),

        // Moyen-Orient & Pays du Golfe
        Currency("AED", "UAE Dirham", "Dirham des Émirats Arabes Unis", "AED", "🇦🇪", "AE", 3.6725),
        Currency("SAR", "Saudi Riyal", "Riyal Saoudien", "SAR", "🇸🇦", "SA", 3.7510),
        Currency("QAR", "Qatari Rial", "Riyal Qatari", "QR", "🇶🇦", "QA", 3.64),
        Currency("KWD", "Kuwaiti Dinar", "Dinar Koweïtien", "KD", "🇰🇼", "KW", 0.306),
        Currency("BHD", "Bahraini Dinar", "Dinar Bahreïni", "BD", "🇧🇭", "BH", 0.376),
        Currency("OMR", "Omani Rial", "Rial Omanais", "OMR", "🇴🇲", "OM", 0.384),
        Currency("JOD", "Jordanian Dinar", "Dinar Jordanien", "JD", "🇯🇴", "JO", 0.709),
        Currency("ILS", "Israeli New Shekel", "Shekel Israélien", "₪", "🇮🇱", "IL", 3.72),
        Currency("LBP", "Lebanese Pound", "Livre Libanaise", "L£", "🇱🇧", "LB", 89500.0),
        Currency("IQD", "Iraqi Dinar", "Dinar Irakien", "IQD", "🇮🇶", "IQ", 1310.0),
        Currency("YER", "Yemeni Rial", "Rial Yéménite", "YR", "🇾🇪", "YE", 250.0),

        // Asie & Pacifique
        Currency("CNY", "Chinese Yuan", "Yuan Chinois", "¥", "🇨🇳", "CN", 7.2350),
        Currency("HKD", "Hong Kong Dollar", "Dollar de Hong Kong", "HK$", "🇭🇰", "HK", 7.8240),
        Currency("TWD", "New Taiwan Dollar", "Nouveau Dollar Taïwanais", "NT$", "🇹🇼", "TW", 32.45),
        Currency("SGD", "Singapore Dollar", "Dollar de Singapour", "S$", "🇸🇬", "SG", 1.3480),
        Currency("INR", "Indian Rupee", "Roupie Indienne", "₹", "🇮🇳", "IN", 83.45),
        Currency("KRW", "South Korean Won", "Won Sud-Coréen", "₩", "🇰🇷", "KR", 1375.0),
        Currency("IDR", "Indonesian Rupiah", "Roupie Indonésienne", "Rp", "🇮🇩", "ID", 16250.0),
        Currency("MYR", "Malaysian Ringgit", "Ringgit Malaisien", "RM", "🇲🇾", "MY", 4.71),
        Currency("THB", "Thai Baht", "Baht Thaïlandais", "฿", "🇹🇭", "TH", 36.65),
        Currency("PHP", "Philippine Peso", "Peso Philippin", "₱", "🇵🇭", "PH", 58.60),
        Currency("VND", "Vietnamese Dong", "Dong Vietnamien", "₫", "🇻🇳", "VN", 25450.0),
        Currency("PKR", "Pakistani Rupee", "Roupie Pakistanaise", "₨", "🇵🇰", "PK", 278.50),
        Currency("BDT", "Bangladeshi Taka", "Taka Bangladais", "৳", "🇧🇩", "BD", 117.50),
        Currency("LKR", "Sri Lankan Rupee", "Roupie Sri-Lankaise", "Rs", "🇱🇰", "LK", 303.0),
        Currency("NPR", "Nepalese Rupee", "Roupie Népalaise", "NPR", "🇳🇵", "NP", 133.50),
        Currency("AFN", "Afghan Afghani", "Afghani Afghan", "Af", "🇦🇫", "AF", 70.80),
        Currency("MMK", "Myanmar Kyat", "Kyat Birman", "K", "🇲🇲", "MM", 2100.0),
        Currency("KHR", "Cambodian Riel", "Riel Cambodgien", "៛", "🇰🇭", "KH", 4095.0),
        Currency("LAK", "Lao Kip", "Kip Laotien", "₭", "🇱🇦", "LA", 21900.0),
        Currency("MNT", "Mongolian Tugrik", "Tugrik Mongol", "₮", "🇲🇳", "MN", 3390.0),
        Currency("BND", "Brunei Dollar", "Dollar de Brunei", "B$", "🇧🇳", "BN", 1.3480),
        Currency("MOP", "Macanese Pataca", "Pataca de Macao", "MOP$", "🇲🇴", "MO", 8.06),
        Currency("MVR", "Maldivian Rufiyaa", "Rufiyaa Maldivienne", "Rf", "🇲🇻", "MV", 15.40),
        Currency("FJD", "Fijian Dollar", "Dollar Fidjien", "FJ$", "🇫🇯", "FJ", 2.26),
        Currency("PGK", "Papua New Guinean Kina", "Kina Papouan-Néo-Guinéen", "K", "🇵🇬", "PG", 3.88),
        Currency("WST", "Samoan Tala", "Tala Samoan", "WS$", "🇼🇸", "WS", 2.75),
        Currency("TOP", "Tongan Paʻanga", "Paʻanga Tongien", "T$", "🇹🇴", "TO", 2.37),
        Currency("VUV", "Vanuatu Vatu", "Vatu Vanuatais", "VT", "🇻🇺", "VU", 120.0),
        Currency("SBD", "Solomon Islands Dollar", "Dollar des Îles Salomon", "SI$", "🇸🇧", "SB", 8.48),

        // Europe (Hors zone Euro)
        Currency("PLN", "Polish Zloty", "Zloty Polonais", "zł", "🇵🇱", "PL", 3.98),
        Currency("TRY", "Turkish Lira", "Livre Turque", "₺", "🇹🇷", "TR", 32.85),
        Currency("HUF", "Hungarian Forint", "Forint Hongrois", "Ft", "🇭🇺", "HU", 365.0),
        Currency("CZK", "Czech Koruna", "Couronne Tchèque", "Kč", "🇨🇿", "CZ", 23.20),
        Currency("RON", "Romanian Leu", "Leu Roumain", "lei", "🇷🇴", "RO", 4.59),
        Currency("BGN", "Bulgarian Lev", "Lev Bulgare", "лв", "🇧🇬", "BG", 1.80),
        Currency("RSD", "Serbian Dinar", "Dinar Serbe", "din.", "🇷🇸", "RS", 108.20),
        Currency("ISK", "Icelandic Króna", "Couronne Islandaise", "kr", "🇮🇸", "IS", 139.50),
        Currency("ALL", "Albanian Lek", "Lek Albanais", "L", "🇦🇱", "AL", 93.50),
        Currency("BAM", "Bosnia-Herzegovina Mark", "Mark Convertible Bosniaque", "KM", "🇧🇦", "BA", 1.80),
        Currency("MKD", "Macedonian Denar", "Denar Macédonien", "ден", "🇲🇰", "MK", 56.80),
        Currency("MDL", "Moldovan Leu", "Leu Moldave", "MDL", "🇲🇩", "MD", 17.75),
        Currency("UAH", "Ukrainian Hryvnia", "Hryvnia Ukrainienne", "₴", "🇺🇦", "UA", 40.50),
        Currency("GEL", "Georgian Lari", "Lari Géorgien", "₾", "🇬🇪", "GE", 2.78),
        Currency("AMD", "Armenian Dram", "Dram Arménien", "֏", "🇦🇲", "AM", 388.0),
        Currency("AZN", "Azerbaijani Manat", "Manat Azerbaïdjanais", "₼", "🇦🇿", "AZ", 1.70),
        Currency("KZT", "Kazakhstani Tenge", "Tenge Kazakh", "₸", "🇰🇿", "KZ", 465.0),
        Currency("UZS", "Uzbekistani Som", "Som Ouzbek", "UZS", "🇺🇿", "UZ", 12600.0),
        Currency("KGS", "Kyrgyzstani Som", "Som Kirghiz", "с", "🇰🇬", "KG", 87.20),
        Currency("TJS", "Tajikistani Somoni", "Somoni Tadjik", "SM", "🇹🇯", "TJ", 10.90),
        Currency("TMT", "Turkmenistani Manat", "Manat Turkmène", "T", "🇹🇲", "TM", 3.50),

        // Amérique Latine & Caraïbes
        Currency("BRL", "Brazilian Real", "Real Brésilien", "R$", "🇧🇷", "BR", 5.4820),
        Currency("MXN", "Mexican Peso", "Peso Mexicain", "Mex$", "🇲🇽", "MX", 18.25),
        Currency("ARS", "Argentine Peso", "Peso Argentin", "$", "🇦🇷", "AR", 920.0),
        Currency("CLP", "Chilean Peso", "Peso Chilien", "CLP$", "🇨🇱", "CL", 940.0),
        Currency("COP", "Colombian Peso", "Peso Colombien", "COL$", "🇨🇴", "CO", 4120.0),
        Currency("PEN", "Peruvian Sol", "Sol Péruvien", "S/.", "🇵🇪", "PE", 3.79),
        Currency("UYU", "Uruguayan Peso", "Peso Uruguayen", "\$U", "🇺🇾", "UY", 40.20),
        Currency("BOB", "Bolivian Boliviano", "Boliviano Bolivien", "Bs.", "🇧🇴", "BO", 6.91),
        Currency("PYG", "Paraguayan Guarani", "Guarani Paraguayen", "₲", "🇵🇾", "PY", 7520.0),
        Currency("CRC", "Costa Rican Colón", "Colón Costaricien", "₡", "🇨🇷", "CR", 525.0),
        Currency("DOP", "Dominican Peso", "Peso Dominicain", "RD$", "🇩🇴", "DO", 59.20),
        Currency("GTQ", "Guatemalan Quetzal", "Quetzal Guatémaltèque", "Q", "🇬🇹", "GT", 7.78),
        Currency("HNL", "Honduran Lempira", "Lempira Hondurien", "L", "🇭🇳", "HN", 24.75),
        Currency("NIO", "Nicaraguan Córdoba", "Córdoba Nicaraguayen", "C$", "🇳🇮", "NI", 36.80),
        Currency("PAB", "Panamanian Balboa", "Balboa Panaméen", "B/.", "🇵🇦", "PA", 1.0),
        Currency("JMD", "Jamaican Dollar", "Dollar Jamaïcain", "J$", "🇯🇲", "JM", 156.0),
        Currency("TTD", "Trinidad & Tobago Dollar", "Dollar de Trinité-et-Tobago", "TT$", "🇹🇹", "TT", 6.78),
        Currency("BBD", "Barbadian Dollar", "Dollar Barbadien", "Bds$", "🇧🇧", "BB", 2.0),
        Currency("BSD", "Bahamian Dollar", "Dollar Bahaméen", "B$", "🇧🇸", "BS", 1.0),
        Currency("BZD", "Belize Dollar", "Dollar Bélizien", "BZ$", "🇧🇿", "BZ", 2.0),
        Currency("GYD", "Guyanese Dollar", "Dollar Guyanien", "G$", "🇬🇾", "GY", 209.0),
        Currency("SRD", "Surinamese Dollar", "Dollar Surinamais", "Sr$", "🇸🇷", "SR", 31.50),
        Currency("HTG", "Haitian Gourde", "Gourde Haïtienne", "G", "🇭🇹", "HT", 132.50),
        Currency("XCD", "East Caribbean Dollar", "Dollar des Caraïbes Orientales", "EC$", "🇦🇬", "XC", 2.70),
        Currency("CUP", "Cuban Peso", "Peso Cubain", "₱", "🇨🇺", "CU", 24.0),
        Currency("VES", "Venezuelan Bolívar", "Bolívar Vénézuélien", "Bs.S", "🇻🇪", "VE", 36.50),
        Currency("ANG", "Netherlands Antillean Guilder", "Florin des Antilles Néerlandaises", "NAƒ", "🇨🇼", "AN", 1.79),
        Currency("AWG", "Aruban Florin", "Florin Arubais", "Afl.", "🇦🇼", "AW", 1.79),
        Currency("BMD", "Bermudian Dollar", "Dollar Bermudien", "BD$", "🇧🇲", "BM", 1.0),
        Currency("KYD", "Cayman Islands Dollar", "Dollar des Îles Caïmans", "CI$", "🇰🇾", "KY", 0.83)
    )

    fun find(code: String): Currency {
        return currencies.firstOrNull { it.code.equals(code, ignoreCase = true) }
            ?: Currency(
                code = code.uppercase(),
                name = code.uppercase(),
                frenchName = code.uppercase(),
                symbol = code.uppercase(),
                flag = "🌐",
                countryCode = code.take(2).uppercase(),
                defaultRateToUSD = 1.0
            )
    }
}
